FROM centos:centos7

LABEL maintainer Alexander Merck <breakfastdub@gmail.com>
LABEL name "dionaea"
LABEL version "0.1"
LABEL release "1"
LABEL summary "Dionaea HoneyPot container"
LABEL description "Dionaea is meant to be a nepenthes successor, embedding python as scripting language, using libemu to detect shellcodes, supporting ipv6 and tls."
LABEL autoritative-source-url "https://github.com/CommunityHoneyNetwork/communityhoneynetwork"
LABEL changelog-url "https://github.com/CommunityHoneyNetwork/communityhoneynetwork/commits/master"

# Set DOCKER var - used by Dionaea init to determine logging
ENV DOCKER "yes"
ENV playbook "dionaea.yml"

RUN yum install -y epel-release \
        && yum install -y ansible
RUN yum groupinstall -y "Development Tools"

