---
  pkgs:
    - git
    - python-virtualenv
    - autoconf
    - automake
    - check
    - libtool
    - curl

  dionaea_repo: http://github.com/dinotools/dionaea

  dionaea_version: 0.7.0

  dionaea_dir: /opt/dionaea
  dionaea_user: dionaea

  runit_service_dir: /etc/service/dionaea